### ISSUE TITLE
Non-uniform period with rotated 2D plane moving through 3D noise

### ISSUE THREAD

**Issue by timmb** [stegu/psrdnoise#13]
Hi Stefan

In the paper you mention that prsdnoise has visible artefacts when moving an axes-aligned 2D plane through 3D space. You suggest rotating the plane to be off the axes.

However, the periods are specified per-axis, so they no longer pair up with the input coordinates.

If I have period `p = (p.x, p.y, p.z)` and a rotation matrix `M`, then will the period of my three axes be `M * p`? If so, is it still possible to specify an exact period for the three rotated dimensions (e.g. by giving the period as `M^-1 * p`)?

If not, then is it possible to define a rotation that resolves the artefacts but still allows an exact period to be specified for the transformed z axis? (so we can make animations loop over time)

Thanks for the help and for the great library!

Tim

**Comment by stegu** [comment]
You can rotate by "rational angles" in all axes to make sure the rotated
pattern tiles (with a different period), but this is a bit tricky even in
2D, and even harder and more restrictive in 3D.

For this use case, I would suggest using the rotated Perlin grid and
specify periods that are multiples of 3. That particular rotation is one of
those "rational angle rotations" that works in 3D. Actually, it's the most
useful and least restrictive one. Use the Perlin rotated simplex grid and
you should be fine. The patent has expired, and it was probably never valid
anyway.

**Comment by timmb** [comment]
Thank you!
